"""Initial migration

Revision ID: c61e9f0d85b1
Revises: 
Create Date: 2021-06-29 16:59:44.389980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61e9f0d85b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pronouns', sa.String(), nullable=True))
    op.add_column('user', sa.Column('url', sa.String(), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(), nullable=True))
    op.add_column('user', sa.Column('bio', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'bio')
    op.drop_column('user', 'location')
    op.drop_column('user', 'url')
    op.drop_column('user', 'pronouns')
    # ### end Alembic commands ###
